import type { NextPage } from 'next'
import Head from 'next/head'
import Navbar from "../components/Navbar/Navbar";


const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Next App Typescript Boilerplate</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
        {/* IMPLEMENT SECTION PADDING FOR ALL */}
        {/* Hero */}
      <div>
        <main>
        </main>
        {/* Hours */}
        {/* GALERIA => INSTAGRAM/META API */}
        {/* Contact */}
      </div>
    </>
  )
}

export default Home