import styled from "styled-components";
import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'

const Title = styled.h1`
  color: red;
`;

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Next App Typescript Boilerplate</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://rsms.me/inter/inter.css" />
      </Head>

      <nav>
        <Link href="/about">
          <a>About</a>
        </Link>
      </nav>

      <main>
      <p>hello</p>
      <Title>Title</Title>
      </main>

      <footer>
        <p>Footer</p>
      </footer>
    </div>
  )
}

export default Home